<?php
/**
 * @var Bss\LensSystem\Block\Adminhtml\Condition\Data $block
 */
?>

<div id="conditionTree"></div>

<script>
    require(['jquery', 'jsTree'], function($){
        $.mage.jsTree({
            stepsData: <?= /** @noEscape */ json_encode($block->getLensSteps()) ?>,
            optionsData: <?= /** @noEscape */ json_encode($block->getLensOptions()) ?>,
            conditionData: <?= /** @noEscape */ json_encode($block->getLensCondition()) ?>,
        });
    })
</script>
