<h2>Reward Point Information</h2>
<hr>
<h3>You are 
     <?php
            /**
             * @var \LoyaltyProgram\RewardPoint\Block\MyPoint $block
             */
          //   echo $block->getCustomerId();

            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            $connection = $resource->getConnection();
            $table = $resource->getTableName('current_vip'); //gives table name

            $sqlEarn = $connection->select('*')->from($table)->where(
                $table . '.entity_id = ' . $block->getCustomerId()
            );
            
            foreach ($connection->fetchAll($sqlEarn) as $row){   
            echo $row['vip'];
            }

     ?></h3>
<h3>You have 
     <?php
            /**
             * @var \LoyaltyProgram\RewardPoint\Block\MyPoint $block
             */
          //   echo $block->getCustomerId();

            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            $connection = $resource->getConnection();
            $table = $resource->getTableName('current_point'); //gives table name

            $sqlEarn = $connection->select('*')->from($table)->where(
                $table . '.entity_id = ' . $block->getCustomerId()
            );
            
            foreach ($connection->fetchAll($sqlEarn) as $row){   
            echo $row['point'];
            }

     ?>
     points</h3>
<p style="font-weight: bold;">Current exchange rate</p>
<p>1 USD = <?php
            /**
             * @var \LoyaltyProgram\RewardPoint\Block\MyPoint $block
             */
          //   echo $block->getCustomerId();

            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            $connection = $resource->getConnection();
            $table = $resource->getTableName('current_vip'); //gives table name
            $tableVip = $resource->getTableName('vip'); //gives table name

            $sqlEarn = $connection->select('*')->from($table)->join(
                   $tableVip, 
                   $table . '.vip = ' . $tableVip . '.vip_name'
               )->where(
                $table . '.entity_id = ' . $block->getCustomerId()
            );
            
            foreach ($connection->fetchAll($sqlEarn) as $row){   
            echo $row['vip_rate'];
            }

        ?> points</p>
<hr>
<h2>Point History</h2>
<br>
<div class="responsive-table">
    <table>
        <thead>
            <tr>
                <th>Point</th>
                <th>Reasson</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        <?php
            /**
             * @var \LoyaltyProgram\RewardPoint\Block\AllActivity $block
             */

            // echo $block->sayHello();

            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            $connection = $resource->getConnection();
            $table = $resource->getTableName('history_point'); //gives table name
            

            $sql = $connection->select('*')->from($table)->where(
                $table . '.entity_id = ' . $block->getCustomerId()
            );
            
            foreach ($connection->fetchAll($sql) as $row){   
            echo "<tr>";
            echo "<td> +" . $row['history_point'] . "</td>";
            echo "<td>" . $row['history_reason'] . "</td>";
            echo "<td>" . $row['history_date'] . "</td>";
            echo "</tr>"; 
            }

        ?>
        </tbody>
    </table>
</div>

